services:
  database:
    image: postgres:17.4
    restart: always
    shm_size: 256mb
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-app_db}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin}
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "${PGADMIN_PORT:-8001}:80"
    networks:
      - app-network
    depends_on:
      - database
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  redis:
    image: redis:alpine
    restart: always
    command: redis-server --save 20 1 --loglevel warning
    ports:
      - "${REDIS_PORT:-6379}:6379"
    networks:
      - app-network
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M

  redis-insight:
    image: redislabs/redisinsight:latest
    restart: always
    ports:
      - "${REDIS_INSIGHT_PORT:-8002}:5540"
    networks:
      - app-network
    volumes:
      - redis_insight_data:/db
    depends_on:
      - redis
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

networks:
  app-network:
    driver: bridge
    name: ${APP_NETWORK_NAME:-app-network}

volumes:
  postgres_data:
    name: ${APP_NAME:-app}_postgres_data
  pgadmin_data:
    name: ${APP_NAME:-app}_pgadmin_data
  redis_data:
    name: ${APP_NAME:-app}_redis_data
  redis_insight_data:
    name: ${APP_NAME:-app}_redis_insight_data